steps:
  # Unity WebGL 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/project'
      - 'game-ci/unity3d:2022.3.16f1-webgl'
      - 'unity-editor'
      - '-batchmode'
      - '-nographics'
      - '-quit'
      - '-projectPath'
      - '/project'
      - '-executeMethod'
      - 'Builder.BuildWebGL'
      - '-logFile'
      - '/project/build.log'
  
  # Storage에 업로드
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - 'builds/WebGL/*'
      - 'gs://nth-glider-443703-g9-unity-builds/'

  # Cloud Run 배포
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'unity-webgl'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  timeout: '3600s'  # 빌드 시간 제한을 1시간으로 설정
